version: 2.1
orbs:
  node: circleci/node@5.0.0
workflows:
  version: 2
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:1.1.2
    steps:
      - checkout
      - node/install:
          node-version: '16.x'
      - node/install-packages:
          with-cache: true
      - run: npm run lint
      - run: npm run build
      - run:
          name: terraform init & plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
      - run:
          name: terraform
          command: |
            cd terraform
            terraform apply -auto-approve tfapply
