version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          with-cache: true
      - run: npm run lint
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
#    working_directory: /tmp/project
    docker:
        - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform init & plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - build
      - deploy:
          requires:
            - build
