version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  build:
    executor:
      name: node/default
      tag: '16.18.1'
    steps:
      - checkout
      - node/install-packages:
          with-cache: true
      - run: npm run lint
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - terraform
  deploy:
    docker:
        - image: docker.mirror.hashicorp.services/hashicorp/terraform:1.1.2
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform init & plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -out tfapply
      - run:
          name: terraform apply
          command: |
            cd terraform
            terraform apply -auto-approve tfapply
workflows:
  version: 2
  deploy_to_prod:
    jobs:
      - build
      - deploy:
          requires:
            - build
